language: csharp
# if your .sln/.csproj file has a different name, change it here :)
solution: ci-example.csproj

jobs:
  include:
    - os: linux
      dist: bionic
    - os: osx
      osx_image: xcode12