language: csharp
# if your .sln/.csproj file has a different name, change it here :)
solution: ci-example.csproj

# Travis CI jobs to run multiple builds
jobs:
  include:
    # linux build with Ubuntu 18.04 "Bionic Beaver"
    # (https://docs.travis-ci.com/user/reference/linux/
    - os: linux 
      dist: bionic
      # .Net Core version 3.1.302
      # (https://dotnet.microsoft.com/download/dotnet-core/3.1)
      dotnet: 3.1.302
    # macOS build with "xcode12" image running macOS 10.15.5 with Xcode 12
    # (https://docs.travis-ci.com/user/reference/osx/)
    - os: osx
      osx_image: xcode12
      # .Net Core version 3.1.302
      # (https://dotnet.microsoft.com/download/dotnet-core/3.1)
      dotnet: 3.1.302
