language: csharp
# if your .sln/.csproj file has a different name, change it here :)
solution: ci-example.csproj

jobs:
  include:
    - os: linux 
      dist: bionic
      dotnet: 3.1.302
    - os: osx
      osx_image: xcode12
      dotnet: latest